### ISSUE TITLE
Autoplay feature request

### ISSUE THREAD

**Issue by alasim** [Emiliano-Bucci/react-spring-carousel#12]

**Comment by alasim** [comment]
I'm not able to autoplay with this awesome slider. Is I'm missing something or this feature isn't available still?

**Comment by doublejosh** [comment]
It's pretty easy to add yourself. This snippet even gives you an `isAutoplayed()` function you can turn off on hover or via some button.

```javascript
  const SLIDE_SPEED = 3500;

  const [isAutoplayed, setIsAutoplayed] = useState(true);
  const autoPlayRef = useRef();

  useEffect(() => {
    if (isAutoplayed) {
      autoPlayRef.current = setInterval(() => {
        slideToNextItem();
      }, SLIDE_SPEED);
    }

    return () => clearInterval(autoPlayRef.current);
  }, [isAutoplayed]);
```

There's a similar idea mentioned for this similar library... https://github.com/gutiguy/react-spring-3d-carousel/issues/64

**Comment by doublejosh** [comment]
I'm unsure why this was marked *completed* because it's not in the library.

**Comment by doublejosh** [comment]
Seems like the `slideToNextItem` does not advance to the end of the slides. It only does the first two. WHAT?!
