### ISSUE TITLE
Storybook issue

### ISSUE THREAD

**Issue by bananafreak** [Emiliano-Bucci/react-spring-carousel#2]
Hey, I am trying to implement react-spring-carousel with storybook and running into following issue:

ERROR in ../node_modules/react-spring-carousel/dist/esm/index.js 1:1678
Module parse failed: Unexpected token (1:1678)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

Any idea how to fix this one?
Thanks!

**Comment by Emiliano-Bucci** [comment]
@bananafreak Hi, and sorry for the delay but i was investigating the issue! It turns out that it was a mistake in my rollup.config :/ If you update to the latest version it should be fixed now :) Please reopen if you need so ;)

**Comment by bananafreak** [comment]
perfect, it's working now, thanks for the prompt response:)
