### ISSUE TITLE
Does it has support for react 18?

### ISSUE THREAD

**Issue by afedorovjs** [Emiliano-Bucci/react-spring-carousel#5]
I get the following error when using nextjs 12.1.4 and react 18
<img width="948" alt="Screenshot 2022-04-06 at 01 26 45" src="https://user-images.githubusercontent.com/54903611/161861149-950c9efb-d941-4afc-adda-a6c5424b8898.png">
.

**Comment by afedorovjs** [comment]
Apparently this beautiful lib doesn't have it yet, with react 17.0.2 it works :(

**Comment by Emiliano-Bucci** [comment]
Hi! I didn't had the time yet to take a look at React 18, but i'm working on it :)

**Comment by Emiliano-Bucci** [comment]
@afedorovjs Hi, and sorry for the delay! Support for React 18 is on! :) -> https://github.com/Emiliano-Bucci/react-spring-carousel/releases/tag/v2.0.13
