### ISSUE TITLE
[feature request] allow renderThumb to take the activeItem as a prop

### ISSUE THREAD

**Issue by eddiew** [Emiliano-Bucci/react-spring-carousel#6]
I want to do some conditional styling of the thumbs, to make it clear which of the current slides is showing. Allowing a function `({activeItem}) => thumb element` instead of just an element for renderThumb would enable this.

Is this something the project is interested in supporting?

**Comment by Emiliano-Bucci** [comment]
@eddiew Hi, and thanks for using the library! :) 

Did you try to use the `useListenToCustomEvent` hook, and pass the `activeItem` as a prop? -> https://react-spring-carousel.emilianobucci.com/docs/events

Internally, `useSpringCarousel` doesn't use `useState` at all (it's all **refs* and **functions**) and i don't like that much the idea of adding it. Instead, if you need, you could easily do it by using `useListenToCustomEvent` inside every thumb component and setting the state (true/false), or you can use `useListenToCustomEvent` outside and pass the `isActive` state value as a prop.

Please let me know if that helps :)

**Comment by PudparK** [comment]
Hey @Emiliano-Bucci , where does `useListenToCustomEvent` come from? I can't seem to get it to work. Is that a React 18 specific hook?

`edit` I didn't see the context part. Rookie mistake. Sorry.

**Comment by pak11273** [comment]
@Emiliano-Bucci You did this in your example [here](https://react-spring-carousel.emilianobucci.com/docs/use-spring-carousel/initial-active-item) but you didn't use thumbs.  Can you show the code for this?

**Comment by asusual1540** [comment]
The best thing of this library is its fully customizable. For those who are trying to apply active style to thumb icons dynamically,

`  const [activeBanner, setActiveBanner] = useState<Number>(0)
  const banner_images: Banner[] = [
    { id: 0, image: "/banner/slider-1.jpg", icon: "/bullet.svg" },
    { id: 1, image: "/banner/slider-2.jpg", icon: "/bullet.svg" },
    { id: 2, image: "/banner/slider-3.jpg", icon: "/bullet.svg" },
    { id: 3, image: "/banner/slider-4.jpg", icon: "/bullet.svg" },
    { id: 4, image: "/banner/slider-5.jpg", icon: "/bullet.svg" }
  ]
  const {
    carouselFragment, thumbsFragment, slideToPrevItem, slideToNextItem, slideToItem, useListenToCustomEvent } = useSpringCarousel({
      withLoop: true,
      withThumbs: true,
      items: banner_images.map((i: any) => ({
        id: i.id,
        renderItem: (
          <div className="fade_to_bottom h-56 sm:h-64 xl:h-144 w-full flex justify-center">
            <Image width={1920} height={1080} className="h-full w-full object-cover object-center" src={`${i.image}`} alt="" priority />
          </div>
        ),
        renderThumb: (
          <span className={`${activeBanner === i.id ? 'opacity-100' : 'opacity-60'}`}
            onClick={() => slideToItem(Number(i.id))}
          >
            <Image src={`${i.icon}`} width={36} height={36} alt="" />
          </span>
        )
      }))
    })

  useListenToCustomEvent((event) => {
    if (event.eventName === "onSlideStartChange") {
      setActiveBanner(event.nextItem.index)
    }
  })
`

**Comment by mehedihasanadnan** [comment]
const [activeBanner, setActiveBanner] = useState<Number>(0)
  const banner_images: Banner[] = [
    { id: 0, image: "/banner/slider-1.jpg", icon: "/bullet.svg" },
    { id: 1, image: "/banner/slider-2.jpg", icon: "/bullet.svg" },
    { id: 2, image: "/banner/slider-3.jpg", icon: "/bullet.svg" },
    { id: 3, image: "/banner/slider-4.jpg", icon: "/bullet.svg" },
    { id: 4, image: "/banner/slider-5.jpg", icon: "/bullet.svg" }
  ]
  const {
    carouselFragment, thumbsFragment, slideToPrevItem, slideToNextItem, slideToItem, useListenToCustomEvent } = useSpringCarousel({
      withLoop: true,
      withThumbs: true,
      items: banner_images.map((i: any) => ({
        id: i.id,
        renderItem: (
          <div className="fade_to_bottom h-56 sm:h-64 xl:h-144 w-full flex justify-center">
            <Image width={1920} height={1080} className="h-full w-full object-cover object-center" src={`${i.image}`} alt="" priority />
          </div>
        ),
        renderThumb: (
          <span className={`cursor-pointer ${activeBanner === i.id ? 'opacity-100' : 'opacity-60'}`}
            onClick={() => slideToItem(Number(i.id))}
          >
            <Image src={`${i.icon}`} width={36} height={36} alt="" />
          </span>
        )
      }))
    })

  useListenToCustomEvent((event) => {
    if (event.eventName === "onSlideStartChange") {
      setActiveBanner(event.nextItem.index)
    }
  })

**Comment by agrattan0820** [comment]
@pak11273 Found the code for his `initialActiveItem` using the thumbs example [here](https://github.com/Emiliano-Bucci/react-spring-carousel-docs/blob/main/src/templates/docs/Examples/useSpringCarousel/InitialActiveItem/index.tsx)!

**Comment by agrattan0820** [comment]
Here's my TS solution for anyone else that stumbles here:
```tsx
type CarouselProps = {
  items: ReactSpringCarouselItem[];
};

const Carousel = ({ items }: CarouselProps) => {
  const [activeItem, setActiveItem] = useState(0);
  const {
    carouselFragment,
    thumbsFragment,
    slideToPrevItem,
    slideToNextItem,
    slideToItem,
    useListenToCustomEvent,
    getCurrentActiveItem,
  } = useSpringCarousel({
    initialActiveItem: 0,
    withLoop: true,
    withThumbs: true,
    items: items.map((item, i) => {
      return {
        ...item,
        renderThumb: (
          <button
            onClick={() => slideToItem(item.id)}
            css={[tw`mx-2 transition-colors`, activeItem === i && tw`text-fire-red`]}
          >
            <BsCircleFill />
          </button>
        ),
      };
    }),
  });

  useListenToCustomEvent((event) => {
    if (event.eventName === "onSlideStartChange") {
      const currActiveItem = getCurrentActiveItem();
      setActiveItem(currActiveItem.index);
    }
  });

return (
  ...
 );
};

export default Carousel;
```
