### ISSUE TITLE
React v18 Dependency

### ISSUE THREAD

**Issue by asb1512** [Emiliano-Bucci/react-spring-carousel#7]
Getting an NPM error when trying to install, looks like react-spring-carousel@2.0.13 requires react@^18.0.0. Does this package really require the new features provided by React v18? I'm of the understanding that React v18 is still in beta and not yet on a stable release.

**Comment by asb1512** [comment]
There is also an additional conflict that requires react-spring@^9.4.5-beta.0 rather than a stable release

**Comment by lambrosx77** [comment]
React 18 is on stable release. You can check it on [github](https://github.com/facebook/react/). 

v2.0.13 was asked for supporting 18 otherwise you can install v.2.0.12 if you prefer staying in React 17.

**Comment by Emiliano-Bucci** [comment]
@asb1512 Hi! Yes, latest version was released only to support React 18; if you can't upgrade it, you can use v.2.0.12, there's no difference at all. Maybe it would've been better to release v.2.0.13 as a beta, and keep latest version for React 17, sorry for that. If that's the case, i can make the change. Please let me know :)

**Comment by asb1512** [comment]
No worries, I went ahead and upgraded it in the end. Maybe have a mention of it or specify which versions work with which version of React in the installation section?

Otherwise, very cool package and the documentation is very well done! Thanks!

**Comment by Emiliano-Bucci** [comment]
@asb1512 Yes sure, you're totally right, and thanks for the feedback! I'm closing this issue, please feel free to re-open if you need something else.
