### ISSUE TITLE
 Change itemsPerSlide 

### ISSUE THREAD

**Issue by Irene-FI** [Emiliano-Bucci/react-spring-carousel#8]
I want to create a responsive slider that changes the number of visible items based on screen dimensions.

Is there a way to reset the itemsPerSlide property ?

**Comment by Emiliano-Bucci** [comment]
@Irene-FI  Hi! You could try this:

```
export function Component() {
  const [itemsPerSlide, setItemsPerSlide] = useState(4);

  useEffect(() => {
    function handleOnChange(event){
      if (event.matches) {
        setItemsPerSlide(2);
      } else {
        setItemsPerSlide(4);
      }
    }
    const isTablet = window.matchMedia('(max-width: 768px)');

    if (isTablet.matches) {
      setItemsPerSlide(2);
    } else {
      setItemsPerSlide(4);
    }

    isTablet.addListener(handleOnChange)
    return () => {
      isTablet.removeListener(handleOnChange)
    }
  }, []);

  return (
    // jsx return...
  );
}
```

 This is how actually is done in the docs site. Let me know if it works :)

**Comment by Irene-FI** [comment]
@Emiliano-Bucci , thanks for the replying.
The suggestion worked. I had to update the listener syntax to remove deprecated warning though

Here's the [code](https://github.com/Irene-FI/responsive-react-carousel) I ended up with, styling was done with tailwind
